## 3.2 Tensors: Multidimensional arrays

**Python list**

In [1]:
a = [1.0, 2.0, 1.0]
print("a =", a)
print("a[0] =", a[0])
a[2] = 3.0
print("a =", a)

a = [1.0, 2.0, 1.0]
a[0] = 1.0
a = [1.0, 2.0, 3.0]


**PyTorch tensor**

In [2]:
import torch
b = torch.ones(3)
print("b =", b)

print("b[1] =", b[1])

print("float(b[2]) =", float(b[2]))

b[1] = 2.0
print("b =", b)

b = tensor([1., 1., 1.])
b[1] = tensor(1.)
float(b[2]) = 1.0
b = tensor([1., 2., 1.])


In [3]:
c = torch.zeros(6)
print("c =", c)
print("c[4] =", c[4])

c[0] = 6
c[1] = 5
c[2] = 4
c[3] = 3
c[4] = 2
c[5] = 1
print("c =", c)
print("c[4] =", c[4])

c = torch.tensor([8.0, 9.0, 10.0, 11.0, 12.0, 13.0])
print("c =", c)
print("c[4] =", c[4])

c = tensor([0., 0., 0., 0., 0., 0.])
c[4] = tensor(0.)
c = tensor([6., 5., 4., 3., 2., 1.])
c[4] = tensor(2.)
c = tensor([ 8.,  9., 10., 11., 12., 13.])
c[4] = tensor(12.)


In [4]:
d = torch.zeros(2, 3)
print("d =\n",d)
print("d[1, 1] =", d[1, 1])
print("d[0] =", d[0])

print("\n")
d = torch.tensor([[2.0, 3.0, 4.0], [3.0, 1.0, 4.0]])
print("d =\n",d)
print("d[1, 1] =", d[1, 1])
print("d[0] =", d[0])

print("\n")
print("d.shape =", d.shape)

d =
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
d[1, 1] = tensor(0.)
d[0] = tensor([0., 0., 0.])


d =
 tensor([[2., 3., 4.],
        [3., 1., 4.]])
d[1, 1] = tensor(1.)
d[0] = tensor([2., 3., 4.])


d.shape = torch.Size([2, 3])


## 3.3 Indexing tensors

In [5]:
e = torch.randint(0, 10, [4, 4])
print("e =\n", e)

print("Without proper specification, all columns are indexed by default.")
print("All rows:\ne[:] =\n", e[:])
print("Row 1 --> (3-1):\ne[1:3] =\n", e[1:3])
print("Row 2 --> end:\ne[2:] =\n", e[2:])
print("Row start --> (4-1):\ne[:4] =\n", e[:4])
print("Row start --> next to last:\ne[:-1] =\n", e[:-1])
print("Row 1 --> (4-1), in step of 2:\ne[1:4:2] =\n", e[1:4:2])

print("\n")
print("Row start --> (2-1), Col 0:\ne[:2, 0] =\n", e[:2, 0])
print("Row 1 --> last, Col start --> (2-1):\ne[1:, :2] =\n", e[1:, :2])
print("Add a dimension of size 1, same to unsqueeze:\ne[None] =\n", e[None])

e =
 tensor([[8, 7, 2, 9],
        [9, 3, 9, 0],
        [3, 4, 8, 5],
        [1, 0, 1, 1]])
Without proper specification, all columns are indexed by default.
All rows:
e[:] =
 tensor([[8, 7, 2, 9],
        [9, 3, 9, 0],
        [3, 4, 8, 5],
        [1, 0, 1, 1]])
Row 1 --> (3-1):
e[1:3] =
 tensor([[9, 3, 9, 0],
        [3, 4, 8, 5]])
Row 2 --> end:
e[2:] =
 tensor([[3, 4, 8, 5],
        [1, 0, 1, 1]])
Row start --> (4-1):
e[:4] =
 tensor([[8, 7, 2, 9],
        [9, 3, 9, 0],
        [3, 4, 8, 5],
        [1, 0, 1, 1]])
Row start --> next to last:
e[:-1] =
 tensor([[8, 7, 2, 9],
        [9, 3, 9, 0],
        [3, 4, 8, 5]])
Row 1 --> (4-1), in step of 2:
e[1:4:2] =
 tensor([[9, 3, 9, 0],
        [1, 0, 1, 1]])


Row start --> (2-1), Col 0:
e[:2, 0] =
 tensor([8, 9])
Row 1 --> last, Col start --> (2-1):
e[1:, :2] =
 tensor([[9, 3],
        [3, 4],
        [1, 0]])
Add a dimension of size 1, same to unsqueeze:
e[None] =
 tensor([[[8, 7, 2, 9],
         [9, 3, 9, 0],
         [3, 4, 8, 5]

## 3.5 Tensor element types

`torch.float32` or `torch.float`: 32-bit floating-point  
`torch.float64` or `torch.double`: 64-bit, double-precision floating-point  
`torch.float16` or `torch.half`: 16-bit, half-precision floating-point  
`torch.int8`: signed 8-bit integers  
`torch.uint8`: unsigned 8-bit integers  
`torch.int16` or `torch.short`: signed 16-bit integers  
`torch.int32` or `torch.int`: signed 32-bit integers  
`torch.int64` or `torch.long`: signed 64-bit integers  
`torch.bool`: Boolean

In [6]:
print("f = torch.ones(3, 2, dtype = torch.float)")
f = torch.ones(3, 2, dtype = torch.float)
# f = torch.ones(3, 2).float()
# f = torch.ones(3, 2).to(torch.float)
# f = torch.ones(3, 2).to(dtype = torch.float)
print("f =\n", f)

print("f.dtype =", f.dtype)

f = torch.ones(3, 2, dtype = torch.float)
f =
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
f.dtype = torch.float32


## Exercise 1: Create a tensor a from list(range(9)). Predict and then check the size, offset, and stride.
### a. Create a new tensor using b = a.view(3, 3). What does view do? Check that a and b share the same storage.
### b. Create a tensor c = b[1:,1:]. Predict and then check the size, offset, and stride.

In [7]:
a = torch.tensor(list(range(9)))
print("a =", a)
print("a.size() =", a.size())
print("a.offset() =", a.storage_offset())
print("a.stride() =", a.stride())

print("\na.")
b = a.view(3, 3)
print("b =\n", b)
print("view accesses the tensor element and reshapes them into a tensor with different size.")
print("a and b share the same storage:", id(a.storage()) == id(b.storage()))

print("\nb.")
c = b[1:, 1:]
print("c =\n", c)
print("c.size() =", c.size())
print("c.offset() =", c.storage_offset())
print("c.stride() =", c.stride())

a = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
a.size() = torch.Size([9])
a.offset() = 0
a.stride() = (1,)

a.
b =
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
view accesses the tensor element and reshapes them into a tensor with different size.
a and b share the same storage: True

b.
c =
 tensor([[4, 5],
        [7, 8]])
c.size() = torch.Size([2, 2])
c.offset() = 4
c.stride() = (3, 1)


## Exercise 2: Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the torch library?
### a. Apply the function element-wise to a. Why does it return an error?
### b. What operation is required to make the function work?
### c. Is there a version of your function that operates in place?

In [8]:
import math
import numpy as np
torsen = torch.rand(3, 3)
print("torsen =\n", torsen)
print("a.")
# torsen_sin = math.sin(torsen)
print("When using math.sin(torsen), it returns")
print("ValueError: only one element tensors can be converted to Python scalars")
print("\nb.")
print("Alternatively, we should use numpy or torch.")

# torsen_sin = np.sin(torsen)
torsen_sin = torch.sin(torsen)
print("torsen_sin =\n", torsen_sin)
print("\nc.")
print("Or operations with a trailing underscore to operate inplace. For example sin_(), sqrt_()")
torsen_sin2 = torsen.sin_()
print("torsen_sin2 =\n", torsen_sin2)


torsen =
 tensor([[0.8172, 0.8648, 0.0287],
        [0.8302, 0.8772, 0.3184],
        [0.4324, 0.2590, 0.9046]])
a.
When using math.sin(torsen), it returns
ValueError: only one element tensors can be converted to Python scalars

b.
Alternatively, we should use numpy or torch.
torsen_sin =
 tensor([[0.7292, 0.7610, 0.0287],
        [0.7381, 0.7689, 0.3130],
        [0.4190, 0.2561, 0.7862]])

c.
Or operations with a trailing underscore to operate inplace. For example sin_(), sqrt_()
torsen_sin2 =
 tensor([[0.7292, 0.7610, 0.0287],
        [0.7381, 0.7689, 0.3130],
        [0.4190, 0.2561, 0.7862]])
